import { describe, test, expect } from 'vitest'
import { render, screen } from '@testing-library/react'
import HypothesisCard from '../src/components/HypothesisCard'

const detectionWindow = {
  window_number: 8,
  window_timestamp: '2024-01-01T00:08:00Z',
  R_score: 3.96,
  confidence: 0.79,
}

const sampleHypothesis = {
  generated_by: 'sample',
  root_service: 'service-b',
  mechanism: 'Scenario mechanism text.',
  cascade_path: 'service-b → service-d → service-f',
  evidence: ['e1', 'e2', 'e3'],
}

const modelHypothesis = {
  generated_by: 'bedrock',
  model_id: 'anthropic.claude-3-haiku-20240307-v1:0',
  root_service: 'checkout-api',
  mechanism: 'Latency and error z-scores rose together.',
  cascade_path: 'checkout-api',
  evidence: ['p99_latency_z sustained 3 windows', 'error_rate_z sustained 2 windows', 'R 3.4'],
}

const renderCard = (hypothesis) =>
  render(
    <HypothesisCard
      hypothesis={hypothesis}
      triggered
      activeWindow={10}
      detectionWindow={detectionWindow}
    />
  )

describe('HypothesisCard provenance', () => {
  test('sample scenario content is explicitly marked as sample data', () => {
    renderCard(sampleHypothesis)

    expect(screen.getByTestId('sample-data-notice')).toBeInTheDocument()
    expect(screen.getByText(/Sample scenario content/)).toBeInTheDocument()
  })

  test('sample content is never attributed to Bedrock or called root-cause analysis', () => {
    const { container } = renderCard(sampleHypothesis)
    const text = container.textContent

    expect(text).not.toMatch(/Generated by Amazon Bedrock/)
    expect(text).not.toMatch(/Root Cause Analysis/)
    expect(text).not.toMatch(/claude-3-haiku/)
  })

  test('a real model output is attributed to its model and not marked as sample', () => {
    const { container } = renderCard(modelHypothesis)

    expect(screen.queryByTestId('sample-data-notice')).not.toBeInTheDocument()
    expect(container.textContent).toMatch(/anthropic\.claude-3-haiku/)
    expect(screen.getByText(/Model-generated summary/)).toBeInTheDocument()
  })
})

describe('HypothesisCard causality claims', () => {
  test('a multi-node path is labelled as scenario-declared, not observed', () => {
    const { container } = renderCard(sampleHypothesis)

    expect(container.textContent).toMatch(/SCENARIO PATH/)
    expect(container.textContent).toMatch(/does not observe dependencies/)
    expect(container.textContent).toMatch(/cannot establish this ordering/)
  })

  test('a single-service model output describes scope rather than a cascade', () => {
    const { container } = renderCard(modelHypothesis)

    expect(container.textContent).toMatch(/SCOPE/)
    expect(container.textContent).not.toMatch(/SCENARIO PATH/)
    expect(container.textContent).toMatch(/evaluates one service at a time/)
    expect(container.textContent).toMatch(/DRIFTING SERVICE/)
  })

  // service-b appears twice: once as the root-service badge and once as a path
  // node, so these assert on counts rather than uniqueness.
  test('the Unicode path renders every node', () => {
    renderCard(sampleHypothesis)

    expect(screen.getAllByText('service-b').length).toBeGreaterThanOrEqual(1)
    expect(screen.getByText('service-d')).toBeInTheDocument()
    expect(screen.getByText('service-f')).toBeInTheDocument()
  })

  test('an ASCII-arrow path renders identically, as a real model response would emit', () => {
    renderCard({ ...sampleHypothesis, cascade_path: 'service-b -> service-d -> service-f' })

    expect(screen.getAllByText('service-b').length).toBeGreaterThanOrEqual(1)
    expect(screen.getByText('service-d')).toBeInTheDocument()
    expect(screen.getByText('service-f')).toBeInTheDocument()
  })
})

describe('HypothesisCard window anchoring', () => {
  test('the detection window is taken from the data, not hardcoded', () => {
    render(
      <HypothesisCard
        hypothesis={modelHypothesis}
        triggered
        activeWindow={9}
        detectionWindow={{ ...detectionWindow, window_number: 5 }}
      />
    )

    expect(screen.getByText('W5')).toBeInTheDocument()
    expect(screen.getByText(/anchored to W5/)).toBeInTheDocument()
  })

  test('nothing renders when detection has not triggered', () => {
    const { container } = render(
      <HypothesisCard
        hypothesis={sampleHypothesis}
        triggered={false}
        activeWindow={10}
        detectionWindow={detectionWindow}
      />
    )

    expect(container).toBeEmptyDOMElement()
  })
})
